Add modal window treatment to macOS
aseprite/laf pull request #116
Opened 2024-12-03 14:01 UTC by Gasparoken

This fix is the first step to solve issue aseprite/aseprite#4561

2024-12-04 12:30 UTC, dacap requested changes

2024-12-04 12:30 UTC, dacap commented on os/osx/window.mm
>      }
We're already setting the level property if it's floating, probably we can have a modal / not floating (this is not the case of Aseprite which sets the "floating" property for all non-main windows):
```suggestion
    if (spec->floating()) {
      self.level = NSFloatingWindowLevel;
      self.hidesOnDeactivate = true;
    }
    if (spec->modal())
      self.level = NSModalPanelWindowLevel;
```

2024-12-04 13:27 UTC, dacap commented on os/osx/window.mm
> +      [self setLevel:NSModalPanelWindowLevel];
```suggestion
      self.level = NSModalPanelWindowLevel;
```

2024-12-09 16:27 UTC, dacap commented
I'll merge this, it would be nice to block the whole hierarchy of parent's floating windows when a modal is displayed, but at the moment this works better than the current `main` to fix the bug.

2024-12-09 16:28 UTC, merged

2024-12-13 15:52 UTC, Gasparoken commented
> I'll merge this, it would be nice to block the whole hierarchy of parent's floating windows when a modal is displayed, but at the moment this works better than the current `main` to fix the bug.

Great! Remember to approve https://github.com/aseprite/aseprite/pull/4835 so that issue https://github.com/aseprite/aseprite/issues/4561 is resolved in Aseprite.